enum KeyAction {
  EDIT_LABEL,
  DELETE_ANNO,
  ENTER_ANNO_ADD_MODE,
  LEAVE_ANNO_ADD_MODE,
  UNDO,
  REDO,
  TRAVERSE_ANNOS,
  CAM_MOVE_UP,
  CAM_MOVE_DOWN,
  CAM_MOVE_LEFT,
  CAM_MOVE_RIGHT,
  CAM_MOVE_STOP,
  COPY_ANNOTATION,
  PASTE_ANNOTATION,
  RECREATE_ANNO,
  DELETE_ANNO_IN_CREATION,
  TOGGLE_ANNO_COMMENT_INPUT,
}

export default KeyAction;
